<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
	<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="PurchaseVendorAppService\**" />
    <Compile Remove="PurchaseVendorDataService\**" />
    <Compile Remove="PurchaseVendorModels\**" />
    <EmbeddedResource Remove="PurchaseVendorAppService\**" />
    <EmbeddedResource Remove="PurchaseVendorDataService\**" />
    <EmbeddedResource Remove="PurchaseVendorModels\**" />
    <None Remove="PurchaseVendorAppService\**" />
    <None Remove="PurchaseVendorDataService\**" />
    <None Remove="PurchaseVendorModels\**" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="BuildOutput\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="PurchaseVendorAppService\PurchaseVendorAppService.csproj" />
    <ProjectReference Include="PurchaseVendorModels\PurchaseVendorModels.csproj" />
  </ItemGroup>

</Project>
